name: contact
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.11.0
  path_provider: ^2.0.11
  image: ^3.0.1
  cupertino_icons: ^1.0.8
  permission_handler: ^10.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/first_ui.png
    - assets/second_figma.png
    - assets/fourt_review_design.png